#!/usr/bin/bash
#
# Script: detect-theme.sh
# Description: Detects the current Xfce style/theme (GTK theme, icon theme,
#              window manager theme, mouse cursor theme + size, font) via
#              xfconf-query, resolves each to an apt package where possible
#              (via dpkg -S), and writes the results to backup/theme.conf.
#
# Usage: ./detect-theme.sh
#
# perform_backup.sh runs this automatically. It can also be run on its own
# whenever you want to refresh the theme snapshot; apply-theme.sh consumes
# backup/theme.conf to replay it on another machine.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
source "$SCRIPT_DIR/lib/common.sh"

require_cmd xfconf-query dpkg

OUT_FILE="$SCRIPT_DIR/backup/theme.conf"
mkdir -p "$(dirname "$OUT_FILE")"

xfconf_get() {
    # xfconf_get <channel> <property>
    xfconf-query -c "$1" -p "$2" 2>/dev/null
}

# Finds the on-disk directory for a theme/icon-set name by checking each
# candidate parent directory in order (user override dirs first).
find_theme_dir() {
    local name="$1"
    shift
    local parent dir
    for parent in "$@"; do
        dir="$parent/$name"
        if [ -d "$dir" ]; then
            echo "$dir"
            return 0
        fi
    done
    return 1
}

# Resolves the apt package that owns a theme directory, if any. Only
# directories under /usr/share can be package-owned -- user dirs (~/.themes,
# ~/.icons) never are, so those are always reported as unresolved.
resolve_package_for_dir() {
    local dir="$1"
    case "$dir" in
        /usr/share/*)
            local probe="$dir"
            [ -f "$dir/index.theme" ] && probe="$dir/index.theme"
            dpkg -S "$probe" 2>/dev/null | head -1 | cut -d: -f1
            ;;
        *)
            return 1
            ;;
    esac
}

detect_one() {
    # detect_one <label> <name> <parent-dirs...>
    # Only the resolved package name goes to stdout (this is captured via
    # $(...) by the caller) -- all diagnostic output must go to stderr,
    # or it would get mixed into the captured value.
    local label="$1" name="$2"
    shift 2
    local dir pkg
    if [ -z "$name" ]; then
        log "  $label: (not set)" >&2
        return
    fi
    if dir="$(find_theme_dir "$name" "$@")"; then
        pkg="$(resolve_package_for_dir "$dir")" || pkg=""
    else
        dir=""
        pkg=""
    fi
    if [ -n "$pkg" ]; then
        log "  $label: $name (package: $pkg)" >&2
    elif [ -n "$dir" ]; then
        log "  $label: $name (no apt package -- found at $dir, will be carried as files)" >&2
    else
        log "  $label: $name (could not locate theme directory on disk)" >&2
    fi
    printf '%s\n' "$pkg"
}

log "Detecting current Xfce theme..."

gtk_theme_name="$(xfconf_get xsettings /Net/ThemeName)"
icon_theme_name="$(xfconf_get xsettings /Net/IconThemeName)"
wm_theme_name="$(xfconf_get xfwm4 /general/theme)"
cursor_theme_name="$(xfconf_get xsettings /Gtk/CursorThemeName)"
cursor_theme_size="$(xfconf_get xsettings /Gtk/CursorThemeSize)"
font_name="$(xfconf_get xsettings /Gtk/FontName)"

theme_parents=("$HOME/.themes" "/usr/share/themes")
icon_parents=("$HOME/.icons" "/usr/share/icons")

gtk_theme_package="$(detect_one "GTK theme" "$gtk_theme_name" "${theme_parents[@]}")"
icon_theme_package="$(detect_one "Icon theme" "$icon_theme_name" "${icon_parents[@]}")"
wm_theme_package="$(detect_one "Window manager theme" "$wm_theme_name" "${theme_parents[@]}")"
cursor_theme_package="$(detect_one "Cursor theme" "$cursor_theme_name" "${icon_parents[@]}")"

log "  Cursor size: ${cursor_theme_size:-(not set)}"
log "  Font: ${font_name:-(not set)}"

cat > "$OUT_FILE" <<EOF
# Auto-generated by detect-theme.sh on $(date -Iseconds). Do not edit by
# hand -- rerun detect-theme.sh to regenerate. Consumed by apply-theme.sh.
#
# A *_PACKAGE var being empty means that theme wasn't traced back to an apt
# package (either hand-installed, or not found on disk at detection time).
# Its files need to already be present via backup-restore-configs-manager.sh
# (which carries ~/.themes and ~/.icons) before apply-theme.sh can use it.

GTK_THEME_NAME="$gtk_theme_name"
GTK_THEME_PACKAGE="$gtk_theme_package"

ICON_THEME_NAME="$icon_theme_name"
ICON_THEME_PACKAGE="$icon_theme_package"

WM_THEME_NAME="$wm_theme_name"
WM_THEME_PACKAGE="$wm_theme_package"

CURSOR_THEME_NAME="$cursor_theme_name"
CURSOR_THEME_PACKAGE="$cursor_theme_package"
CURSOR_THEME_SIZE="$cursor_theme_size"

FONT_NAME="$font_name"
EOF

log "Theme snapshot written to $OUT_FILE"
